filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/apache/access.log
    - /var/log/apache/error.log
    - /var/log/app/*.log*
    - /var/log/postgresql/*.log

output.elasticsearch:
  enabled: true
  hosts: ["host.docker.internal:9200"]
  username: "elastic"
  password: "changeme"
  indices:
  - index: "apache-%{+yyyy.MM.dd}"
    when.equals:
      event.module: "apache"
  - index: "postgres-%{+yyyy.MM.dd}"
    when.equals:
      event.module: "postgresql"
  - index: "app-%{+yyyy.MM.dd}"
    when.contains:
      log.file.path: "/var/log/app/"

filebeat.modules:
- module: apache
  access:
    enabled: true
    var.paths: ["/var/log/apache/access.log"]
  error:
    enabled: true
    var.paths: ["/var/log/apache/error.log"]
- module: postgresql
  log:
    enabled: true
    var.paths: ["/var/log/postgresql/postgresql-*.log"]
- module: redis
  log:
    enabled: true
    var.paths: ["/var/log/redis/redis-server.log*"]
  slowlog:
    enabled: true
    var.hosts: ["host.docker.internal:6378"]
    var.password: "admin"
