version: "3.2"
services:

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/log/mysql/mysql.log --slow-query-log=1 --long-query-time=1 --slow-query-log-file=/var/log/mysql/mysql-slow.log
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    image: bitnami/redis:6.2.6
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1G

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    depends_on:
      - redis
    restart: always
    environment:
    - REDIS_HOSTS=redis:host.docker.internal:6379
    ports:
    - "8081:8081"

  flower:
    image: mher/flower:0.9.7
    container_name: flower
    depends_on:
      - redis
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://host.docker.internal:6379/0
      CELERY_RESULT_BACKEND: redis://host.docker.internal:6379/1
    volumes:
    - flower_data:/data
    deploy:
      resources:
        limits:
          memory: 1G

  app:
    image: app
    container_name: app
    depends_on:
      - mysql
      - redis
    restart: always
    volumes:
    - apache_log:/var/log/apache2
    - app_log:/var/log/app
    ports:
    - "8080:80"

volumes:
  mysql_data:
  mysql_log:
  apache_log:
  app_log:
  flower_data:
