version: "3.2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    depends_on:
      - postgres
      - app
      - redis
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1G

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    container_name: filebeat
    depends_on:
      - elasticsearch
    restart: unless-stopped
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - apache_log:/var/log/apache:ro
      - postgres_log:/var/log/postgresql:ro
      - redis_log:/var/log/redis:ro
      - app_log:/var/log/app:ro
    command: ["filebeat", "-e", "-strict.perms=false"]
    deploy:
      resources:
        limits:
          memory: 1G

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    depends_on:
      - elasticsearch
    restart: unless-stopped
    ports:
      - 5601:5601
    links:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 1G

  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/log/postgresql
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql/", "-c", "log_statement=all"]

  redis:
    image: bitnami/redis:6.2.6
    container_name: redis
    command: redis-server --protected-mode no --loglevel warning --logfile /var/log/redis/redis-server.log
    restart: always
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      #- REDIS_MASTER_PASSWORD="${REDIS_MASTER_PASSWORD}"
      - REDIS_PASSWORD="admin"
      - REDIS_AOF_ENABLED=no
    volumes:
    - redis_log:/var/log/redis
    user: root # for write log permissions
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1G

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    depends_on:
      - redis
    restart: always
    environment:
    - REDIS_HOSTS=redis:host.docker.internal:6379
    - REDIS_PASSWORD="admin"
    ports:
    - "8081:8081"

  app:
    image: app
    container_name: app
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
    - apache_log:/var/log/apache2
    - app_log:/var/log/app
    ports:
    - "8080:80"
    #environment:
    #- SET_CONTAINER_TIMEZONE=true
    #- TZ=Etc/UTC

volumes:
  postgres_data:
  postgres_log:
  apache_log:
  app_log:
  elasticsearch_data:
  redis_log:
